version: '3.1'

services:
  database:
    image: mysql:5.7
    container_name: "auth-manager"
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_manager
      MYSQL_USER: auth_manager_user
      MYSQL_PASSWORD: password
    volumes:
      - auth-man-db:/var/lib/mysql

  jaeger:
    container_name: "auth_jaeger"
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABKED: true
    ports:
      - "6831:6831/udp"
      - "6833:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  nats:
    image: 'nats:latest'
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    container_name: nats-server
    command: "-js"


volumes:
  auth-man-db: